name: test

on: push

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1

  call:
    needs: init
    uses: ./.github/workflows/callable.yml

  dependent:
    if: always()
    needs: call
    runs-on: ubuntu-latest
    env:
      CALL_JSON: ${{ toJson(needs.call) }}
    steps:
      - run: |
          echo "${CALL_JSON}"
