name: test

on: push

jobs:
  m:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        e: [a, b, c]
    outputs:
      foo: ${{ steps.o.outputs.foo }}
    steps:
      - id: o
        env:
          E: ${{ matrix.e }}
        run: |
          if [ "${E}" -eq 'b' ]; then
            echo "foo=bar" >> "$GITHUB_OUTPUT"
          fi

  d:
    needs: m
    runs-on: ubuntu-latest
    steps:
      - env:
          FOO: ${{ needs.m.outputs.foo }}
        run: |
          echo "${FOO}"
